### PR TITLE
Revert internal data structure to simple hash

### LINKED ISSUE #251: Array data structure leading to multiple bugs
@PikachuEXE noted in [this comment](https://github.com/panorama-ed/memo_wise/issues/238#issuecomment-992134835):

> Now I am getting random `memo_wise`ed methods returning unexpected values on each request (e.g. `nil` returned for methods with objects, method expected one class returning object of another class)
>
> Not sure how to reproduce with minimal example yet
>
> Update 1: Sometimes it returns value like `{[[], {}]=>nil}` which seems to be what's used in caching

In our own codebase we're seeing MemoWise v1.4 yielding this type of error as well. It appears to be yet another case of multiple methods sharing the same `index` on the same object, despite attempts to fix this type of issue in both v1.3 and v1.4. What @PikachuEXE describes above is a zero-argument method returning the data structure for a multi-argument method, but we also see it in reverse, with methods that take arguments getting `true` in the array and attempting to use it as their intermediate hash, leading to ``undefined method `[]' for true:TrueClass``.

In addition, we've noticed at least one _other_ (🙀) type of error: `SystemStackError: stack level too deep` occurring when somehow the `klass.send(method_name)` does not invoke the method defined with `klass.module_eval` and so the `send` recursively calls itself forever.

### PR DESCRIPTION
**Pull request by JacobEvelyn**
Previous versions of `MemoWise` used an array as the
internal cache data structure, where each memoized method
uses a unique array index. However, complex inheritance
structures make it easy to have multiple methods accidentally
share the same array index on the same object, resulting
in nondeterministic and incorrect behavior.

While we may explore that optimization again in the future,
for the time being we are switching to a hash data structure
keyed on method name, which is safer because two methods
cannot share the same name in Ruby.

Fixes #251 

**Before merging:**

- [ ] Copy the table printed at the end of the latest benchmark results into the `README.md` and update this PR
- [x] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)

### CODE REVIEW

**Review by jemmaissroff — APPROVED** [review]

File: benchmarks/benchmarks.rb [hunk 1]
```diff
@@ -132,9 +124,7 @@ def positional_splat_keyword_and_double_splat_args(a, *args, b:, **kwargs)
 #
 # NOTE: The proportion of falsey results is 1/N_UNIQUE_ARGUMENTS (because for
 # the methods with arguments we are truthy for all but the first unique argument
-# set, and for zero-arity methods we manually execute `no_args` N_TRUTHY_RESULTS
-# times per each execution of `no_args_falsey`). This number was selected as the
-# lowest number such that this logic:
```
Comment (ms-ati) [inline benchmarks/benchmarks.rb:137]: @JacobEvelyn why remove the falsey tests from the benchmarks -- just not clear if this is on purpose?

**Review by ms-ati — APPROVED** [review]
LGTM

**Comment by JacobEvelyn** [comment]
Thank you @PikachuEXE !

**Comment by PikachuEXE** [comment]
I just notice the branch name is `back-to-the-future`... 🤣
