### PR TITLE
Fix module's `.included` not run sometimes

### LINKED ISSUE #386: 1.12.0 causes undefined method error
Sample app: https://github.com/PikachuEXE/vite-plugin-erb-issue-5-mvp (too lazy to create new sample app

https://github.com/PikachuEXE/vite-plugin-erb-issue-5-mvp/commit/afdfc897c2303784bca3dd1d7f51d1a6b2fcec5f

`rails test` will fail with 1.12.0 but not 1.11.0

Image

### PR DESCRIPTION
**Pull request by PikachuEXE**
Fixes #386

Let me know if test case can be arranged better (I spent most time figuring out what's the cause and how to reproduce in test case form

**Before merging:**

- [x] Copy the table printed at the end of the latest benchmark results into the `README.md` and update this PR
- [x] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)

### CODE REVIEW

File: spec/memo_wise_spec.rb [hunk 1]
```diff
@@ -483,6 +483,58 @@ def child_class_method
...
+        let(:instance) { Klass.new }
+
+        before(:each) do
+          stub_const("ModuleToBeIncludedInAnotherModule", module_to_be_included_in_another_module)
+          stub_const("ModuleToBeIncludedInClass", module_to_be_included_in_class)
+          stub_const("Klass", klass)
+        end
+
+        it "runs `.included` in modules" do
+          expect(instance.send(:method1)).to be true
```
Comment (PikachuEXE) [inline spec/memo_wise_spec.rb:535]: Mistake when simplifying spec
```suggestion
          expect(instance.send(:method1)).to be false
```

**Review by JacobEvelyn — CHANGES_REQUESTED** [review]
Generally looks good other than the small test change I noted.

Would you mind also:

- Squashing this into a single commit (with `Fixes #386` in the commit description)
- Adding this to the changelog (something along the lines of:
```
- Prevented overwriting of `included` in modules prepending `MemoWise` [[#387]](https://github.com/panorama-ed/memo_wise/pull/387))
```

- Updating the benchmarks table in the `README.md` to this from the CI run:

```markdown
|Method arguments|`alt_memery` (2.1.0)|`dry-core`\* (1.1.0)|`memery` (1.7.0)|`memoist3` (1.0.0)|`short_circu_it` (0.29.3)|
|--|--|--|--|--|--|
|`()` (none)|12.20x|0.57x|3.31x|2.76x|18.45x|
|`(a)`|9.75x|0.98x|3.76x|14.54x|13.96x|
|`(a, b)`|7.59x|0.82x|2.92x|11.39x|10.87x|
|`(a:)`|14.89x|0.97x|6.39x|19.76x|12.60x|
|`(a:, b:)`|12.64x|0.86x|5.43x|21.05x|10.70x|
|`(a, b:)`|12.25x|0.84x|5.22x|16.12x|10.31x|
|`(a, *args)`|1.89x|0.65x|0.73x|2.84x|2.70x|
|`(a:, **kwargs)`|2.86x|0.71x|1.21x|4.79x|2.42x|
|`(a, *args, b:, **kwargs)`|1.81x|0.62x|0.83x|3.03x|1.52x|
```

**Comment by PikachuEXE** [comment]
All done

**Review by JacobEvelyn — APPROVED** [review]
Looks good! Thanks for getting this out so quickly and making those changes. ❤️
