### PR TITLE
Fix memoization with inheritance

### LINKED ISSUE #262: Cannot use memoized class level method in sub classes
```ruby

require "memo_wise"

module M1
  module Concern
    def self.included(includer)
      includer.extend ClassMethods
    end
  end

  module ClassMethods
    prepend MemoWise

    # This rarely changed
    # So should be fine caching on first usage
    def class_level_method
      1 + 1
    end
    memo_wise :class_level_method
  end
end

class C1
  include M1::Concern

  def instance_level_method
    self.class.class_level_method + 1
  end
end

class C2 < C1
  # Empty
end

# These are fine
C1.class_level_method
C1.new.instance_level_method

# These are not
C2.class_level_method
C2.new.instance_level_method
```

I use this pattern in my controllers
C1 would be `ApplicationController` and C2 would be my any of the used controllers
M1 would be any of the app-wise shared controller mixin modules

### PR DESCRIPTION
**Pull request by jemmaissroff**
Fixes #262 

**Before merging:**

- [ ] Copy the table printed at the end of the latest benchmark results into the `README.md` and update this PR
- [ ] If this change merits an update to `CHANGELOG.md`, add an entry following Keep a Changelog [guidelines](https://keepachangelog.com/en/1.0.0/) with [semantic versioning](https://semver.org/)

### CODE REVIEW

File: spec/inheritance_spec.rb [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+          "class_method"
+        end
+
+        def instance_method
+          "instance_method"
+        end
+      end
+    end
+
+    it { expect(subject.class_method).to eq("class_method") }
```
Comment (jemmaissroff) [inline spec/inheritance_spec.rb:21]: These two tests were unrelated to the specific issue, just seemed helpful to include

File: spec/inheritance_spec.rb [hunk 2]
```diff
@@ -0,0 +1,43 @@
...
+      memo_wise :class_method
+    end
+
+    let(:inherited_klass) do
+      Class.new do
+        extend module_with_class_method
+      end
+    end
+
+    it { expect(subject.class_method).to eq("class_method") }
```
Comment (jemmaissroff) [inline spec/inheritance_spec.rb:41]: Confirmed that this test was previously failing

File: spec/inheritance_spec.rb [hunk 3]
```diff
@@ -0,0 +1,47 @@
+# frozen_string_literal: true
+
+RSpec.describe "inheritance" do # rubocop:disable RSpec/DescribeClass
```
Comment (JacobEvelyn) [inline spec/inheritance_spec.rb:3]: I don't feel too strongly but I have a preference for keeping these tests in the `spec/memo_wise_spec.rb` file because we have a whole host of other inheritance examples in there and I find it easier to mentally sort out what cases we've tested (for example, this isn't just "simple inheritance," it's also class methods defined with `self.` as opposed to the other types of methods we support).

Thoughts?

Comment (jemmaissroff) [reply spec/inheritance_spec.rb:3]: I think it's more clear in a separate file (and could even migrate the existing ones here). The existing ones are inserted as parts of other contexts instead of all in one place, and I think it's more straightforward to keep inheritance as its own set of specs. Let me know your thoughts

File: spec/memo_wise_spec.rb [hunk 4]
```diff
@@ -630,6 +630,45 @@ def self.module_method; end
...
+            end
+            memo_wise :module1_method
+          end
+        end
+
+        let(:child_class) do
+          Class.new(parent_class)
+        end
+
+        let(:instance) { child_class.new }
```
Comment (JacobEvelyn) [inline spec/memo_wise_spec.rb:661]: Do we need `instance` at all?

**Review by JacobEvelyn — APPROVED** [review]
LGTM if:

1. you remove `instance` (or correct me if I'm missing something).
2. you confirm that the test fails without your fix (which I think it does but just want to make sure since it's been a while).

**Comment by jemmaissroff** [comment]
> 1. you remove `instance` (or correct me if I'm missing something).
Done!

> 2. you confirm that the test fails without your fix (which I think it does but just want to make sure since it's been a while).
Confirmed!
